Name: debug

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Update Module.prop
        run: |
          ORIGIN_VER=$(grep 'version=' module.prop | cut -d'=' -f2)
          DATE_NUM=$(echo "$ORIGIN_VER" | tr -cd '0-9')
          COMMIT_ID=$(git rev-parse --short HEAD)
          
          sed -i "s/^versionCode=.*/versionCode=$DATE_NUM/" module.prop
          sed -i "s/^version=.*/version=${ORIGIN_VER}(${COMMIT_ID})/" module.prop

      - name: Get Version
        id: get_version
        run: |
          echo "version=$(grep -oP 'version=\K[^ ]+' module.prop)" >> "$GITHUB_OUTPUT"

      - name: Generate Asset
        run: |
          sudo mkdir -p /box_for_root
          sudo cp -r --parents $(find ./ -type f ! -path './.git/*' ! -name 'CHANGELOG.md' ! -name 'LICENSE' ! -name 'update.json' ! -name 'build.sh' ! -path './.github/*')  /box_for_root/

      - name: Upload Debug Asset => (box_for_root_${{ steps.get_version.outputs.version }})
        uses: actions/upload-artifact@v7
        with:
          name: "box_for_root_${{ steps.get_version.outputs.version }}"
          path: /box_for_root/

  upload:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Check for [ci] in commit message
        id: check_ci
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMIT_MSG"
          if [[ "$COMMIT_MSG" == *"[ci]"* ]]; then
            echo "should_upload=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_upload=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run build
        if: steps.check_ci.outputs.should_upload == 'true'
        run: |
          ORIGIN_VER=$(grep 'version=' module.prop | cut -d'=' -f2)
          DATE_NUM=$(echo "$ORIGIN_VER" | tr -cd '0-9')
          COMMIT_ID=$(git rev-parse --short HEAD)
          NEW_VER="${ORIGIN_VER}(${COMMIT_ID})"
          
          sed -i "s/^versionCode=.*/versionCode=$DATE_NUM/" module.prop
          sed -i "s/^version=.*/version=$NEW_VER/" module.prop
          
          zip -r -o -X -ll box_for_root-${NEW_VER}.zip ./ \
            -x '.git/*' -x 'CHANGELOG.md' -x 'LICENSE' -x 'update.json' -x 'build.sh' -x '.github/*'

      - name: Upload to GitHub Pre-release
        if: steps.check_ci.outputs.should_upload == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(cat module.prop | grep 'version=' | awk -F '=' '{print $2}')
          FILE=$(find . -name "*.zip")
          gh release create "pre-${VERSION}" "$FILE" \
            --prerelease \
            --title "Pre-release ${VERSION}" \
            --notes "pre-release build from commit $(git log -1 --pretty=%h)"

      - name: Upload to Telegram (Debug Mode)
        if: steps.check_ci.outputs.should_upload == 'true'
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          export VERSION=$(grep 'version=' module.prop | awk -F '=' '{print $2}')
          export COMMIT="Pre-release"
          export DATE=$(TZ='Asia/Shanghai' date "+%Y-%m-%d %H:%M")
          export CHANGELOG="$(git log -1 --pretty=%B | head -n 1)"
          
          FILE=$(find . -name "*.zip" | head -n 1)
          if [ -z "$FILE" ]; then
            echo "[-] Error: No zip file found!"
            exit 1
          fi

          echo "[+] Preparing to upload: $FILE (Version: $VERSION, Commit: $COMMIT)"
          pip3 install --quiet telethon==1.31.1
          python3 .github/boxrootbot.py "$FILE"